// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410012712_AddWave2ForeignKeysAndIndexes")]
    partial class AddWave2ForeignKeysAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.AutomationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmailsThisWeek")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AutomationStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailsThisWeek = 0,
                            Enabled = false
                        });
                });

            modelBuilder.Entity("Backend.Models.BoardingPlacement", b =>
                {
                    b.Property<int>("BoardingPlacementId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ActualCheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActualCheckOut")
                        .HasColumnType("date");

                    b.Property<string>("BedLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildrenSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfidentialResidentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("ExpectedCheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpectedCheckOut")
                        .HasColumnType("date");

                    b.Property<string>("PlacementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Sensitivities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialConsiderations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardingPlacementId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("BoardingPlacements");
                });

            modelBuilder.Entity("Backend.Models.BoardingStandingOrder", b =>
                {
                    b.Property<int>("BoardingStandingOrderId")
                        .HasColumnType("int");

                    b.Property<int>("BoardingPlacementId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardingStandingOrderId");

                    b.HasIndex("BoardingPlacementId");

                    b.ToTable("BoardingStandingOrders");
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("date");

                    b.Property<string>("DonationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.HasIndex("SupporterId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AllocationDate")
                        .HasColumnType("date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountAllocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DonationId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("DonationId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("DonationAllocations");
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AttendanceRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProgressPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("EducationRecords");
                });

            modelBuilder.Entity("Backend.Models.EmailTemplate", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            TemplateId = "loyal",
                            Body = "{{first_name}},\n\nYou are making a difference. We are so grateful for your commitment to these girls. You are one of our best supporters — your {{frequency}} heartfelt donations have helped fund {{program_area}}, supported girls through some of their hardest moments, and kept our doors open for those who need us most.\n\nWe are growing more than ever and working to reach more girls across the Philippines. Right now we are in need of funding for {{program_area}}, and even a donation of {{suggested_amount}} would help us get closer to our goal. Anything you give goes a long way to protecting our girls.\n\n{{donate_button}}\n\n— Lunas Project",
                            Description = "3+ gifts — partner-level tone",
                            LastEdited = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastEditedBy = "system",
                            Name = "Loyal Donors",
                            Subject = "You're making a difference, {{first_name}}",
                            Trigger = "frequency >= 3"
                        },
                        new
                        {
                            TemplateId = "first_time",
                            Body = "{{first_name}},\n\nYou are making a difference. Thank you for your generous gift to Lunas Foundation — it means more than you know. Your donation has gone toward {{program_area}}, directly supporting girls who had nowhere else to turn.\n\nWe are growing and working hard to reach even more girls who need us. A donation of {{suggested_amount}} would help us continue that work. Every contribution, no matter the size, goes directly to protecting and empowering the girls in our care.\n\n{{donate_button}}\n\n— Lunas Project",
                            Description = "1-2 gifts — welcome tone",
                            LastEdited = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastEditedBy = "system",
                            Name = "First-Time Donors",
                            Subject = "{{first_name}}, your gift is already making an impact",
                            Trigger = "frequency <= 2"
                        },
                        new
                        {
                            TemplateId = "win_back",
                            Body = "{{first_name}},\n\nYou made a difference — and we haven't forgotten it. Your past generosity helped fund {{program_area}} and supported girls during some of their most vulnerable moments. That gift mattered then, and it still matters now.\n\nA lot has happened since your last donation. We are reaching more girls than ever and growing every month — but we need supporters like you to keep going. Even a gift of {{suggested_amount}} would help us continue the work you helped start.\n\n{{donate_button}}\n\n— Lunas Project",
                            Description = "90+ days since last gift — reactivation tone",
                            LastEdited = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastEditedBy = "system",
                            Name = "Win-Back",
                            Subject = "We miss you, {{first_name}}",
                            Trigger = "recency > 90"
                        });
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bmi")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NutritionScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ResidentId");

                    b.ToTable("HealthWellbeingRecords");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .HasColumnType("int");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("bit");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitationId");

                    b.HasIndex("ResidentId");

                    b.ToTable("HomeVisitations");
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("DonationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("DonationId");

                    b.ToTable("InKindDonationItems");
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedStaffDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedStaffUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("TargetValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanId");

                    b.HasIndex("ResidentId");

                    b.ToTable("InterventionPlans");
                });

            modelBuilder.Entity("Backend.Models.OutreachEmailLog", b =>
                {
                    b.Property<int>("OutreachEmailLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutreachEmailLogId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupporterId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutreachEmailLogId");

                    b.ToTable("OutreachEmailLogs");
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AssignmentStart")
                        .HasColumnType("date");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.ToTable("PartnerAssignments");
                });

            modelBuilder.Entity("Backend.Models.PipelineResult", b =>
                {
                    b.Property<int>("PipelineResultId")
                        .HasColumnType("int");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PipelineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("PipelineResultId");

                    b.ToTable("PipelineResults");
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .HasColumnType("int");

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("bit");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordingId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ProcessRecordings");
                });

            modelBuilder.Entity("Backend.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.ToTable("PublicImpactSnapshots");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("bit");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PwdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("bit");

                    b.HasKey("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SafehouseId");

                    b.ToTable("Safehouses");
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("MonthEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MonthStart")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("int");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("MetricId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("SafehouseMonthlyMetrics");
                });

            modelBuilder.Entity("Backend.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgViewDurationSeconds")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("int");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("int");

                    b.Property<int?>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int");

                    b.Property<decimal?>("EngagementRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("bit");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("Forwards")
                        .HasColumnType("int");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("bit");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("bit");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("int");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostHour")
                        .HasColumnType("int");

                    b.Property<string>("PostType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("int");

                    b.Property<int?>("Reach")
                        .HasColumnType("int");

                    b.Property<int?>("Saves")
                        .HasColumnType("int");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shares")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int");

                    b.Property<decimal?>("WatchTimeSeconds")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PostId");

                    b.ToTable("SocialMediaPosts");
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .HasColumnType("int");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupporterType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.BoardingPlacement", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.BoardingStandingOrder", b =>
                {
                    b.HasOne("Backend.Models.BoardingPlacement", null)
                        .WithMany()
                        .HasForeignKey("BoardingPlacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.HasOne("Backend.Models.Supporter", null)
                        .WithMany()
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.HasOne("Backend.Models.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.HasOne("Backend.Models.Donation", null)
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.HasOne("Backend.Models.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.HasOne("Backend.Models.Safehouse", null)
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
