// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DonationDate")
                        .HasColumnType("date");

                    b.Property<string>("DonationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImpactUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferralPostId")
                        .HasColumnType("int");

                    b.Property<int?>("SupporterId")
                        .HasColumnType("int");

                    b.HasKey("DonationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Backend.Models.DonationAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AllocationDate")
                        .HasColumnType("date");

                    b.Property<string>("AllocationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DonationId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.ToTable("DonationAllocations");
                });

            modelBuilder.Entity("Backend.Models.EducationRecord", b =>
                {
                    b.Property<int>("EducationRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AttendanceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationRecordId");

                    b.ToTable("EducationRecords");
                });

            modelBuilder.Entity("Backend.Models.HealthWellbeingRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("DentalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<decimal?>("EnergyLevelScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GeneralHealthScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("MedicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NutritionScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("PsychologicalCheckupDone")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SleepQualityScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HealthRecordId");

                    b.ToTable("HealthWellbeingRecords");
                });

            modelBuilder.Entity("Backend.Models.HomeVisitation", b =>
                {
                    b.Property<int>("VisitationId")
                        .HasColumnType("int");

                    b.Property<string>("FamilyCooperationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyMembersPresent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUpNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("FollowUpNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationVisited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<bool?>("SafetyConcernsNoted")
                        .HasColumnType("bit");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitationId");

                    b.ToTable("HomeVisitations");
                });

            modelBuilder.Entity("Backend.Models.InKindDonationItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("DonationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedUnitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceivedCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("InKindDonationItems");
                });

            modelBuilder.Entity("Backend.Models.IncidentReport", b =>
                {
                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FollowUpRequired")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("IncidentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("Backend.Models.InterventionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CaseConferenceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("ServicesProvided")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("TargetValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanId");

                    b.ToTable("InterventionPlans");
                });

            modelBuilder.Entity("Backend.Models.Partner", b =>
                {
                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Backend.Models.PartnerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("AssignmentEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AssignmentStart")
                        .HasColumnType("date");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibilityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.ToTable("PartnerAssignments");
                });

            modelBuilder.Entity("Backend.Models.ProcessRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .HasColumnType("int");

                    b.Property<bool?>("ConcernsFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmotionalStateObserved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ProgressNoted")
                        .HasColumnType("bit");

                    b.Property<bool?>("ReferralMade")
                        .HasColumnType("bit");

                    b.Property<int?>("ResidentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("SessionNarrative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordingId");

                    b.ToTable("ProcessRecordings");
                });

            modelBuilder.Entity("Backend.Models.PublicImpactSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("MetricPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.ToTable("PublicImpactSnapshots");
                });

            modelBuilder.Entity("Backend.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("AgeUponAdmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedSocialWorker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseControlNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentRiskLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateCaseStudyPrepared")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateColbObtained")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateColbRegistered")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateEnrolled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfAdmission")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool?>("FamilyIndigenous")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyInformalSettler")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyIs4ps")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilyParentPwd")
                        .HasColumnType("bit");

                    b.Property<bool?>("FamilySoloParent")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSpecialNeeds")
                        .HasColumnType("bit");

                    b.Property<string>("InitialCaseAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialRiskLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPwd")
                        .HasColumnType("bit");

                    b.Property<string>("LengthOfStay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PwdType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferringAgencyPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReintegrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReintegrationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeedsDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SubCatAtRisk")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatChildLabor")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatChildWithHiv")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatCicl")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatOrphaned")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatOsaec")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatPhysicalAbuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatSexualAbuse")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatStreetChild")
                        .HasColumnType("bit");

                    b.Property<bool?>("SubCatTrafficked")
                        .HasColumnType("bit");

                    b.HasKey("ResidentId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("Backend.Models.Safehouse", b =>
                {
                    b.Property<int>("SafehouseId")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityGirls")
                        .HasColumnType("int");

                    b.Property<int?>("CapacityStaff")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SafehouseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SafehouseId");

                    b.ToTable("Safehouses");
                });

            modelBuilder.Entity("Backend.Models.SafehouseMonthlyMetric", b =>
                {
                    b.Property<int>("MetricId")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveResidents")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgEducationProgress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgHealthScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HomeVisitationCount")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("MonthEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MonthStart")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessRecordingCount")
                        .HasColumnType("int");

                    b.Property<int?>("SafehouseId")
                        .HasColumnType("int");

                    b.HasKey("MetricId");

                    b.ToTable("SafehouseMonthlyMetrics");
                });

            modelBuilder.Entity("Backend.Models.SocialMediaPost", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgViewDurationSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BoostBudgetPhp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CallToActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaptionLength")
                        .HasColumnType("int");

                    b.Property<int?>("ClickThroughs")
                        .HasColumnType("int");

                    b.Property<int?>("Comments")
                        .HasColumnType("int");

                    b.Property<string>("ContentTopic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonationReferrals")
                        .HasColumnType("int");

                    b.Property<decimal?>("EngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EstimatedDonationValuePhp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("FeaturesResidentStory")
                        .HasColumnType("bit");

                    b.Property<int?>("FollowerCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("Forwards")
                        .HasColumnType("int");

                    b.Property<bool?>("HasCallToAction")
                        .HasColumnType("bit");

                    b.Property<string>("Hashtags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Impressions")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBoosted")
                        .HasColumnType("bit");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentionsCount")
                        .HasColumnType("int");

                    b.Property<int?>("NumHashtags")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformPostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostHour")
                        .HasColumnType("int");

                    b.Property<string>("PostType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfileVisits")
                        .HasColumnType("int");

                    b.Property<int?>("Reach")
                        .HasColumnType("int");

                    b.Property<int?>("Saves")
                        .HasColumnType("int");

                    b.Property<string>("SentimentTone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shares")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberCountAtPost")
                        .HasColumnType("int");

                    b.Property<int?>("VideoViews")
                        .HasColumnType("int");

                    b.Property<decimal?>("WatchTimeSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PostId");

                    b.ToTable("SocialMediaPosts");
                });

            modelBuilder.Entity("Backend.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .HasColumnType("int");

                    b.Property<string>("AcquisitionChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FirstDonationDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupporterType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
